FROM alphine:3

# Perintah RUN just one-off (satu kali dijalankan)
RUN mkdir hallo
# print halo bro lalu masukkan string tsb kedlm hallo/halobro.txt
RUN echo "halo bro">"hallo/halobro.txt"
RUN cat "hallo/halobro.txt"